spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
   # url: jdbc:mysql://172.16.3.112/wechat?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://192.168.2.204/wechat?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell