spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://172.16.3.112/wechat?characterEncoding=utf-8&useSSL=false
    # url: jdbc:mysql://192.168.2.204/wechat?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell

wechat:
  mpAppId: wx9dc1bacb928a3680
  mpAppSecret: 8d1e2b543e36096894e93e0ed647f601
  mchId: 1483469312
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://nneswn.natappfree.cc/sell/pay/notify

